### ISSUE TITLE
The project is missing the actual package metadata file

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/7.6-Starter-Kit#11]
I'm in the process of cleaning up this solution so that the website is part of the sln, that it uses Nuget and that a new comer can get up and running very quickly by opening the sln and pressing F5. 

I would also like to automate the build process of this to output the Umbraco package file like I do in Articulate (https://shazwazza.com/post/powershell-script-to-create-an-umbraco-package-in-umbraco-s-package-file-format/) ... but the actual package manifest file that creates the package is missing from Git 

Can you please add this file?

**Comment by hartvig** [comment]
Done

**Comment by Shazwazza** [comment]
SupaTak! 

I'll have a play with the solution again tomorrow
