### ISSUE TITLE
This starter kit relies on another 3rd party Umbraco package "Terratype"

### ISSUE THREAD

**Issue by Shazwazza** [umbraco/7.6-Starter-Kit#13]
This package relies on another 3rd party package for map functionality. This is something that is currently not supported by the Umbraco packaging system and means that it will need to ship with all of the other packages files. This would mean that the original package would then have difficultly installing and uninstalling would also cause problems.

Currently the solution as-is does not work because the package files for these 3rd party packages are not included and the strongly typed models for Models Builder also relies on these files.

Can we update our starter kit package to not rely on 3rd party packages?

**Comment by hartvig** [comment]
@Shazwazza it needs to rely on Terratype (and Nested Content), so either it needs to work as-is (the build package works fine?) or the core needs to be improved.

**Comment by Shazwazza** [comment]
We can't easily make the core support having dependencies between packages as we'll be re-making Nuget :P (viva Nuget for Umbraco packages ... one day :) )

Is the Nested Content that it's relying on the one in the Core or in the package?

If we include all of this Terratype packages inside of this package my concerns are:

* the Terratype packages will not be listed as installed packages
* a user can install the Terratype packages separately - I don't know if this will overwrite or ignore what is already there?
* if a user uninstalls the Terratype package after installing it separately it will break the starter kit since all of it's files will be removed
* if the Terratype package is updated, this starter kit doesn't get updated so we'll need to maintain our own release of Terratype packages which are included in ours
* if a user installs a Terratype package and updates to a newer one than we ship with, than we ship a newer version of the starter kit but haven't updated to the latest Terratype package - what happens? Potentially the Terratype package is downgraded and the user won't know about it
* These Terratype packages are also install-able via Nuget so there can be other ways that the above updates can happen

If we aren't that concerned about the above than Ok, otherwise we could try:

* Make copies of the Terratype folders in App_Plugins like Umbraco.SampleSite.Terratype and change the manifest installed to have a different property editor alias than the Terratype default
** But an underlying problem will be that Terratype ships with DLLs so we can't really duplicate those

Otherwise, we could perhaps update the package system to flag folders that are part of a package as 'unofficial' so that they don't get removed when uninstalling the package that contains 'unofficial' files/folders and so that any 'official' files in the real package will always replace any 'unofficial' ones in another package.

**Comment by hartvig** [comment]
Nested Content isn't in the core (yet), so it's a package.

For now I don't see any of this as a (real) concern. The primary goal of the Starter Kit is that people have a great heads start with Umbraco and a decent way to experience its potential.

For now we'll just have to accept the limitations of the core, know that they'll improve and that this Starter Kit including the functionality added by Terratype and Nested Content is heaps better than what we've had before.

**Comment by hartvig** [comment]
BTW: It's *never* the intention that you'd use the Starter Kit in any other way than via the Umbraco package (ie. the purpose of this project is solely to maintain the development of the Starter Kit and not meant for "consumption" of the Starter kit).

**Comment by Shazwazza** [comment]
Ok cool. I'll run some tests tomorrow though to make sure that if people do install Terratype packages after they install Umbraco with the Starterkit that at least the Terratype files overwrite the ones that are already there. If they don't we may need to make changes to the core.

I'll need to update the solution to include all the right files (since the DLL is missing). Will probably actually be much easier to use Nuget to install these packages for this solution and then I can automate the umbraco package creation

I need you to commit you createdpackages file though https://github.com/umbraco/7.6-Starter-Kit/issues/11

**Comment by Shazwazza** [comment]
One 'easier' thing we could do is we could include some metadata as part of the package.xml that indicates to the Umbraco Core packager that this package contains other packages. Then if that is detected it will write to the /App_Data/packages/installed/installedPackages.config file for the other contained packages

**Comment by jonrandahl** [comment]
Hey, just throwing myself into this as I'd like to see where this goes with package dependencies. :-D

While I completely agree with Shannon's

> We can't easily make the core support having dependencies between packages as we'll be re-making Nuget :P (viva Nuget for Umbraco packages ... one day :) )

comment!

With the core handling things the way it does, I wonder if there might be a way to use a package action to handle the download and installation of any dependency instead?

Again, please excuse my ignorance, I'm just thinking out loud and am happy to learn other ways this could happen!

Thanks for all your hard work, both of you, I cannot say that enough! 

Level 10 #h5yr!

**Comment by Shazwazza** [comment]
Thanks for the feedback :)

I'm sure we could do something like that but in effect that is almost the same as just putting the dependencies in the manifest - and creating a Nuget. I would certainly be a cool thing to have and at face value it doesn't seem too difficult... but when things start getting complicated and developers require specific version dependencies both between their own packages and based on the umbraco min version requirement. The way package actions currently work could not facilitate this unfortunately since that would require several appdomain restarts and package actions and the way they are executed are not designed for that. Even if we changed the way package actions execute to handle this sort of thing there's a problem with it failing at any part of the process and the user will not get notified of any problems since package actions do not faciliate any UI feedback to the user.

To do this - even as a first step - this logic would need to be baked into the packager so that the whole process can be reported on. If we change that in core, then that could potentially for for a first step. The package action would also need to take into account circular references of packages.
